In [16]:
import pandas as pd
import numpy as np
import joblib
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model, load_model

In [3]:
with open('/content/pipeline.pkl', 'rb') as file_1:
    pipeline= joblib.load(file_1)
model_func_tune= load_model('/content/model.h5')

In [12]:
data = {
        'membership_category': ['Basic Membership', 'Silver Membership', 'Silver Membership', 'Platinum Membership',
        'Silver Membership', 'No Membership', 'Silver Membership', 'Silver Membership',
        'Platinum Membership', 'Premium Membership'],
        'joined_through_referral': ['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'No'],
        'feedback': ['Poor Website', 'User Friendly Website', 'Reasonable Price', 'Too many ads', 'Poor Website',
        'No reason specified', 'Too many ads', 'Poor Website', 'Quality Customer Care',
        'Poor Product Quality'],
        'avg_transaction_value': [15605.13, 19081.39, 93277.02, 4077.22, 30902.91, 43607.21, 23656.03, 2463.04,
        83402.80, 23132.62],
        'avg_frequency_login_days': [9.0, 11.0, 0.0, 28.0, 14.0, 21.0, 27.0, 10.0, 9.0, 26.0],
        'points_in_wallet': [656.010000, 788.720000, 1119.763538, 742.490000, 647.770000, 637.010000, 696.220000,
        699.370000, 21.225000, 1217.663912]
}
df = pd.DataFrame(data)
df

,membership_category,joined_through_referral,feedback,avg_transaction_value,avg_frequency_login_days,points_in_wallet
0,Basic Membership,Yes,Poor Website,15605.13,9.0,656.010000
1,Silver Membership,No,User Friendly Website,19081.39,11.0,788.720000
2,Silver Membership,No,Reasonable Price,93277.02,0.0,1119.763538
3,Platinum Membership,Yes,Too many ads,4077.22,28.0,742.490000
4,Silver Membership,No,Poor Website,30902.91,14.0,647.770000
5,No Membership,Yes,No reason specified,43607.21,21.0,637.010000
6,Silver Membership,No,Too many ads,23656.03,27.0,696.220000
7,Silver Membership,No,Poor Website,2463.04,10.0,699.370000
8,Platinum Membership,No,Quality Customer Care,83402.80,9.0,21.225000
9,Premium Membership,No,Poor Product Quality,23132.62,26.0,1217.663912

In [13]:
df= pipeline.transform(df)

In [19]:
y_pred_func_tuned = model_func_tune.predict(df)
y_pred_func_tuned = np.where(y_pred_func_tuned >=0.5, 1, 0)
y_pred_func_tuned

1/1 [==============================] - 0s 22ms/step

array([[1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0]])